Module2 task1
htmlacademy-adaptive/1806381-cat-energy-23 pull request #2
Opened 2021-07-27 16:17 UTC by Yuri-Stim

2021-07-27 16:26 UTC, ZubkoWhatislove requested changes

2021-07-27 16:26 UTC, ZubkoWhatislove commented on source/img/icon_alarm.svg
> +<svg width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg">
разные кейсы в картинках

такого быть не должно

лучше все делать через `kebab-case`

2021-07-27 16:26 UTC, ZubkoWhatislove commented on source/index.html
> +      <div class="indicators__list">
элемент без блока

2021-07-27 16:26 UTC, ZubkoWhatislove commented on source/index.html
> +    <div class="offer offer__background">
элемент без блока

2021-07-27 16:26 UTC, ZubkoWhatislove commented on source/index.html
> +        <h2 class="text-block__title">Функциональное питание для котов</h2>
элемент без блока

2021-07-27 16:26 UTC, ZubkoWhatislove commented on source/index.html
> +    <div class="well__list">
элемент без блока

2021-07-27 19:15 UTC, Yuri-Stim commented on source/img/icon_alarm.svg
> +<svg width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Имеется ввиду разный стиль названия картинок?

2021-07-27 19:36 UTC, Yuri-Stim commented on source/index.html
> +      <div class="indicators__list">
Если я правильно понял тут должно быть class="example__indicators-list" или просто class="example__list" и так далее?

2021-07-27 19:39 UTC, Yuri-Stim commented on source/index.html
> +    <div class="offer offer__background">
Тут блоком является "offer"

2021-07-27 19:41 UTC, Yuri-Stim commented on source/index.html
> +        <h2 class="text-block__title">Функциональное питание для котов</h2>
<h2 class="offer__title">Функциональное питание для котов</h2> тут видимо так правильней?

2021-07-27 19:42 UTC, Yuri-Stim commented on source/index.html
> +        <h2 class="text-block__title">Функциональное питание для котов</h2>
class="offer__title"

2021-07-27 19:44 UTC, Yuri-Stim commented on source/index.html
> +    <div class="well__list">
class="offer__button offer__button--mobile" ?

2021-07-28 04:35 UTC, ZubkoWhatislove commented on source/img/icon_alarm.svg
> +<svg width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Верно

2021-07-28 04:36 UTC, ZubkoWhatislove commented on source/index.html
> +    <div class="offer offer__background">
Нельзя что бы шел на одном элемент блок и эломент этого же блока
(если были бы они разные, то можно было)

2021-07-28 04:36 UTC, ZubkoWhatislove commented on source/index.html
> +        <h2 class="text-block__title">Функциональное питание для котов</h2>
Верно

2021-07-28 04:36 UTC, ZubkoWhatislove commented on source/index.html
> +    <div class="well__list">
смотря как ты захочешь это сделать дальше

или продолжение блока, или создание нового

2021-07-28 04:37 UTC, ZubkoWhatislove commented on source/index.html
> +      <div class="indicators__list">
В БЭМе сначала должен быть блок, а потом элемент

.item
  .item__title

просто элемента, без блока быть не может

.item__title

2021-07-28 11:31 UTC, ZubkoWhatislove requested changes

2021-07-28 11:31 UTC, ZubkoWhatislove commented on source/img/thin-cat.svg
> +<svg width="200" height="211" viewBox="0 0 200 211" fill="none" xmlns="http://www.w3.org/2000/svg">
по прежнему есть файлы в разных кейсах
переименую их все в один тип. Советую в `kebab-case`

2021-07-28 11:31 UTC, ZubkoWhatislove commented on source/index.html
> +    <div class="well__list">
Не пофикшенно

2021-07-28 11:31 UTC, ZubkoWhatislove commented on source/index.html
> +    <a class=" page-header__logo_desktop" href="#">
На этих двух что-то явно не так

2021-07-28 18:55 UTC, what1s1ove approved these changes
👍

2021-07-28 18:55 UTC, merged